export const Login = {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE'
}

export const User = {
    FETCH_ALL_USER: 'FETCH_ALL_USER',
    FETCH_ALL_USER_SUCCESS: 'FETCH_ALL_USER_SUCCESS',
    FETCH_ALL_USER_FAILURE: 'FETCH_ALL_USER_FAILURE',

    FETCH_SINGLE_USER: 'FETCH_SINGLE_USER',
    FETCH_SINGLE_USER_SUCCESS: 'FETCH_SINGLE_USER_SUCCESS',
    FETCH_SINGLE_USER_FAILURE: 'FETCH_SINGLE_USER_FAILURE',

    CREATE_USER: 'CREATE_USER',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',

    UPDATE_USER: 'UPDATE_USER',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',

    DELETE_USER: 'DELETE_USER',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',
}

export const Category = {
    FETCH_ALL_CATEGORY: 'FETCH_ALL_CATEGORY',
    FETCH_ALL_CATEGORY_SUCCESS: 'FETCH_ALL_CATEGORY_SUCCESS',
    FETCH_ALL_CATEGORY_FAILURE: 'FETCH_ALL_CATEGORY_FAILURE',

    FETCH_SINGLE_CATEGORY: 'FETCH_SINGLE_CATEGORY',
    FETCH_SINGLE_CATEGORY_SUCCESS: 'FETCH_SINGLE_CATEGORY_SUCCESS',
    FETCH_SINGLE_CATEGORY_FAILURE: 'FETCH_SINGLE_CATEGORY_FAILURE',

    CREATE_CATEGORY: 'CREATE_CATEGORY',
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_FAILURE: 'CREATE_CATEGORY_FAILURE',

    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
    UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_FAILURE: 'UPDATE_CATEGORY_FAILURE',

    DELETE_CATEGORY: 'DELETE_CATEGORY',
    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_FAILURE: 'DELETE_CATEGORY_FAILURE',
}

export const Product = {
    FETCH_ALL_PRODUCT: 'FETCH_ALL_PRODUCT',
    FETCH_ALL_PRODUCT_SUCCESS: 'FETCH_ALL_PRODUCT_SUCCESS',
    FETCH_ALL_PRODUCT_FAILURE: 'FETCH_ALL_PRODUCT_FAILURE',

    FETCH_TRANSACTION_PRODUCT: 'FETCH_TRANSACTION_PRODUCT',
    FETCH_TRANSACTION_PRODUCT_SUCCESS: 'FETCH_TRANSACTION_PRODUCT_SUCCESS',
    FETCH_TRANSACTION_PRODUCT_FAILURE: 'FETCH_TRANSACTION_PRODUCT_FAILURE',

    FETCH_SINGLE_PRODUCT: 'FETCH_SINGLE_PRODUCT',
    FETCH_SINGLE_PRODUCT_SUCCESS: 'FETCH_SINGLE_PRODUCT_SUCCESS',
    FETCH_SINGLE_PRODUCT_FAILURE: 'FETCH_SINGLE_PRODUCT_FAILURE',

    CREATE_PRODUCT: 'CREATE_PRODUCT',
    CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_FAILURE: 'CREATE_PRODUCT_FAILURE',

    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAILURE: 'UPDATE_PRODUCT_FAILURE',

    DELETE_PRODUCT: 'DELETE_PRODUCT',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE',

    DELETE_PERMANENT_PRODUCT: 'DELETE_PERMANENT_PRODUCT',
    DELETE_PERMANENT_PRODUCT_SUCCESS: 'DELETE_PERMANENT_PRODUCT_SUCCESS',
    DELETE_PERMANENT_PRODUCT_FAILURE: 'DELETE_PERMANENT_PRODUCT_FAILURE',
}

export const Transaction = {
    FETCH_ALL_TRANSACTION: 'FETCH_ALL_TRANSACTION',
    FETCH_ALL_TRANSACTION_SUCCESS: 'FETCH_ALL_TRANSACTION_SUCCESS',
    FETCH_ALL_TRANSACTION_FAILURE: 'FETCH_ALL_TRANSACTION_FAILURE',

    FETCH_SINGLE_TRANSACTION: 'FETCH_SINGLE_TRANSACTION',
    FETCH_SINGLE_TRANSACTION_SUCCESS: 'FETCH_SINGLE_TRANSACTION_SUCCESS',
    FETCH_SINGLE_TRANSACTION_FAILURE: 'FETCH_SINGLE_TRANSACTION_FAILURE',

    CREATE_TRANSACTION: 'CREATE_TRANSACTION',
    CREATE_TRANSACTION_SUCCESS: 'CREATE_TRANSACTION_SUCCESS',
    CREATE_TRANSACTION_FAILURE: 'CREATE_TRANSACTION_FAILURE',

    UPDATE_TRANSACTION: 'UPDATE_TRANSACTION',
    UPDATE_TRANSACTION_SUCCESS: 'UPDATE_TRANSACTION_SUCCESS',
    UPDATE_TRANSACTION_FAILURE: 'UPDATE_TRANSACTION_FAILURE',

    DELETE_TRANSACTION: 'DELETE_TRANSACTION',
    DELETE_TRANSACTION_SUCCESS: 'DELETE_TRANSACTION_SUCCESS',
    DELETE_TRANSACTION_FAILURE: 'DELETE_TRANSACTION_FAILURE',

    DELETE_PERMANENT_TRANSACTION: 'DELETE_PERMANENT_TRANSACTION',
    DELETE_PERMANENT_TRANSACTION_SUCCESS: 'DELETE_PERMANENT_TRANSACTION_SUCCESS',
    DELETE_PERMANENT_TRANSACTION_FAILURE: 'DELETE_PERMANENT_TRANSACTION_FAILURE',

    FETCH_DASHBOARD: 'FETCH_DASHBOARD',
    FETCH_DASHBOARD_SUCCESS: 'FETCH_DASHBOARD_SUCCESS',
    FETCH_DASHBOARD_FAILURE: 'FETCH_DASHBOARD_FAILURE',
}

export const Setting = {
    FETCH_SETTING: 'FETCH_SETTING',
    FETCH_SETTING_SUCCESS: 'FETCH_SETTING_SUCCESS',
    FETCH_SETTING_FAILURE: 'FETCH_SETTING_FAILURE',

    UPDATE_SETTING: 'UPDATE_SETTING',
    UPDATE_SETTING_SUCCESS: 'UPDATE_SETTING_SUCCESS',
    UPDATE_SETTING_FAILURE: 'UPDATE_SETTING_FAILURE',
}